//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarThunderParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarThunderParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrical.
        /// </summary>
        public static string bnt_ToMetrical {
            get {
                return ResourceManager.GetString("bnt_ToMetrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btn_Compare_Add {
            get {
                return ResourceManager.GetString("btn_Compare_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string btn_Compare_Remove {
            get {
                return ResourceManager.GetString("btn_Compare_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Excel.
        /// </summary>
        public static string btn_Excel {
            get {
                return ResourceManager.GetString("btn_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string btn_Help {
            get {
                return ResourceManager.GetString("btn_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string btn_Open {
            get {
                return ResourceManager.GetString("btn_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string btn_Preferences {
            get {
                return ResourceManager.GetString("btn_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string btn_Start {
            get {
                return ResourceManager.GetString("btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string btn_Stop {
            get {
                return ResourceManager.GetString("btn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial(UK).
        /// </summary>
        public static string btn_ToImperial {
            get {
                return ResourceManager.GetString("btn_ToImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string common_apply {
            get {
                return ResourceManager.GetString("common_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string common_cancel {
            get {
                return ResourceManager.GetString("common_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string common_error {
            get {
                return ResourceManager.GetString("common_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of critical recorder.
        /// </summary>
        public static string critical_recorder_error {
            get {
                return ResourceManager.GetString("critical_recorder_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string dlg_CS_btn_Add {
            get {
                return ResourceManager.GetString("dlg_CS_btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string dlg_CS_btn_Remove {
            get {
                return ResourceManager.GetString("dlg_CS_btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude in feets.
        /// </summary>
        public static string dlg_CS_cb_AltFeets {
            get {
                return ResourceManager.GetString("dlg_CS_cb_AltFeets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy into Excel only selected fields.
        /// </summary>
        public static string dlg_CS_cb_ExcelSelectedOnly {
            get {
                return ResourceManager.GetString("dlg_CS_cb_ExcelSelectedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use filters.
        /// </summary>
        public static string dlg_CS_cb_Filters {
            get {
                return ResourceManager.GetString("dlg_CS_cb_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outliers filter.
        /// </summary>
        public static string dlg_CS_cb_Outlier {
            get {
                return ResourceManager.GetString("dlg_CS_cb_Outlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string dlg_CS_g_Filters {
            get {
                return ResourceManager.GetString("dlg_CS_g_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout, ms:.
        /// </summary>
        public static string dlg_CS_lbl_ConnectionTimeout {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request delay, ms:.
        /// </summary>
        public static string dlg_CS_lbl_Delay {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If delay is 0 next request will be send after previous will be completed.
        /// </summary>
        public static string dlg_CS_lbl_DelayNote {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_DelayNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpolation interval, ms:.
        /// </summary>
        public static string dlg_CS_lbl_Interpolation {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data capture settings.
        /// </summary>
        public static string dlg_CS_Title {
            get {
                return ResourceManager.GetString("dlg_CS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional grid on.
        /// </summary>
        public static string dlg_GS_cb_AddGrid {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AddGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis colors are same as curves.
        /// </summary>
        public static string dlg_GS_cb_AxisColor {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AxisColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis titles.
        /// </summary>
        public static string dlg_GS_cb_AxisLbl {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AxisLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main grid on.
        /// </summary>
        public static string dlg_GS_cb_MainGrid {
            get {
                return ResourceManager.GetString("dlg_GS_cb_MainGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show legend.
        /// </summary>
        public static string dlg_GS_cb_ShowLegend {
            get {
                return ResourceManager.GetString("dlg_GS_cb_ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string dlg_GS_cb_UseSmoothing {
            get {
                return ResourceManager.GetString("dlg_GS_cb_UseSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string dlg_GS_g_Grid {
            get {
                return ResourceManager.GetString("dlg_GS_g_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string dlg_GS_g_Legend {
            get {
                return ResourceManager.GetString("dlg_GS_g_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing.
        /// </summary>
        public static string dlg_GS_g_Smoothing {
            get {
                return ResourceManager.GetString("dlg_GS_g_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size:.
        /// </summary>
        public static string dlg_GS_lbl_Font {
            get {
                return ResourceManager.GetString("dlg_GS_lbl_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of smoothing, pixels:.
        /// </summary>
        public static string dlg_GS_lbl_SmoothLevel {
            get {
                return ResourceManager.GetString("dlg_GS_lbl_SmoothLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs preferences.
        /// </summary>
        public static string dlg_GS_Title {
            get {
                return ResourceManager.GetString("dlg_GS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use:
        ///- Press Start or F9 to begin data collection in battle/test flight. Before you start check &quot;Altitude in feets&quot; setting;
        ///
        ///- To finish collection press Stop or F10
        ///
        ///- For data copying into Excel press appropriate button or use Ctrl+C/Ctrl+V.
        ///
        ///- PREFERENCES: At data collection preferences it is possible to add or remove input data filters. They blocks collection of data from fields with same names. Exact names you can check at http://127.0.0.1:8111/indicators and http://127.0.0.1:8111/state. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dlg_Help_Content {
            get {
                return ResourceManager.GetString("dlg_Help_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis:.
        /// </summary>
        public static string lbl_Ordinata {
            get {
                return ResourceManager.GetString("lbl_Ordinata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to show.
        /// </summary>
        public static string lbl_Params {
            get {
                return ResourceManager.GetString("lbl_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection failed.
        /// </summary>
        public static string recorder_failed {
            get {
                return ResourceManager.GetString("recorder_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to save.
        /// </summary>
        public static string save_error {
            get {
                return ResourceManager.GetString("save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection in progress. Press Stop or F10 to finish..
        /// </summary>
        public static string state_collecting {
            get {
                return ResourceManager.GetString("state_collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection finished with errors. Press start or F9 to collect new data..
        /// </summary>
        public static string state_failed {
            get {
                return ResourceManager.GetString("state_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorder {0} finished collection with error: {1}.
        /// </summary>
        public static string state_recorder_failed_format {
            get {
                return ResourceManager.GetString("state_recorder_failed_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection finished successfully! Press Start or F9 to collect new data..
        /// </summary>
        public static string state_success {
            get {
                return ResourceManager.GetString("state_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string tab_Compare {
            get {
                return ResourceManager.GetString("tab_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string tab_Data {
            get {
                return ResourceManager.GetString("tab_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphs.
        /// </summary>
        public static string tab_Graph {
            get {
                return ResourceManager.GetString("tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        public static string tab_Measures {
            get {
                return ResourceManager.GetString("tab_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WTParser v1.1.1.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
