//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarThunderParser.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarThunderParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Metrical.
        /// </summary>
        public static string bnt_ToMetrical {
            get {
                return ResourceManager.GetString("bnt_ToMetrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string btn_Compare_Add {
            get {
                return ResourceManager.GetString("btn_Compare_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string btn_Compare_Remove {
            get {
                return ResourceManager.GetString("btn_Compare_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To Excel.
        /// </summary>
        public static string btn_Excel {
            get {
                return ResourceManager.GetString("btn_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        public static string btn_Help {
            get {
                return ResourceManager.GetString("btn_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string btn_Open {
            get {
                return ResourceManager.GetString("btn_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preferences.
        /// </summary>
        public static string btn_Preferences {
            get {
                return ResourceManager.GetString("btn_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        public static string btn_Start {
            get {
                return ResourceManager.GetString("btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        public static string btn_Stop {
            get {
                return ResourceManager.GetString("btn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Imperial(UK).
        /// </summary>
        public static string btn_ToImperial {
            get {
                return ResourceManager.GetString("btn_ToImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string common_apply {
            get {
                return ResourceManager.GetString("common_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string common_cancel {
            get {
                return ResourceManager.GetString("common_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        public static string common_error {
            get {
                return ResourceManager.GetString("common_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error of critical recorder.
        /// </summary>
        public static string critical_recorder_error {
            get {
                return ResourceManager.GetString("critical_recorder_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string dlg_CS_btn_Add {
            get {
                return ResourceManager.GetString("dlg_CS_btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string dlg_CS_btn_Remove {
            get {
                return ResourceManager.GetString("dlg_CS_btn_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Altitude in feets.
        /// </summary>
        public static string dlg_CS_cb_AltFeets {
            get {
                return ResourceManager.GetString("dlg_CS_cb_AltFeets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy into Excel only selected fields.
        /// </summary>
        public static string dlg_CS_cb_ExcelSelectedOnly {
            get {
                return ResourceManager.GetString("dlg_CS_cb_ExcelSelectedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use filters.
        /// </summary>
        public static string dlg_CS_cb_Filters {
            get {
                return ResourceManager.GetString("dlg_CS_cb_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Outliers filter.
        /// </summary>
        public static string dlg_CS_cb_Outlier {
            get {
                return ResourceManager.GetString("dlg_CS_cb_Outlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filters.
        /// </summary>
        public static string dlg_CS_g_Filters {
            get {
                return ResourceManager.GetString("dlg_CS_g_Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection timeout, ms:.
        /// </summary>
        public static string dlg_CS_lbl_ConnectionTimeout {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request delay, ms:.
        /// </summary>
        public static string dlg_CS_lbl_Delay {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If delay is 0 next request will be send after previous will be completed.
        /// </summary>
        public static string dlg_CS_lbl_DelayNote {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_DelayNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interpolation interval, ms:.
        /// </summary>
        public static string dlg_CS_lbl_Interpolation {
            get {
                return ResourceManager.GetString("dlg_CS_lbl_Interpolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data capture settings.
        /// </summary>
        public static string dlg_CS_Title {
            get {
                return ResourceManager.GetString("dlg_CS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional grid on.
        /// </summary>
        public static string dlg_GS_cb_AddGrid {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AddGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Axis colors are same as curves.
        /// </summary>
        public static string dlg_GS_cb_AxisColor {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AxisColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Axis titles.
        /// </summary>
        public static string dlg_GS_cb_AxisLbl {
            get {
                return ResourceManager.GetString("dlg_GS_cb_AxisLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main grid on.
        /// </summary>
        public static string dlg_GS_cb_MainGrid {
            get {
                return ResourceManager.GetString("dlg_GS_cb_MainGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show legend.
        /// </summary>
        public static string dlg_GS_cb_ShowLegend {
            get {
                return ResourceManager.GetString("dlg_GS_cb_ShowLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на On.
        /// </summary>
        public static string dlg_GS_cb_UseSmoothing {
            get {
                return ResourceManager.GetString("dlg_GS_cb_UseSmoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grid.
        /// </summary>
        public static string dlg_GS_g_Grid {
            get {
                return ResourceManager.GetString("dlg_GS_g_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legend.
        /// </summary>
        public static string dlg_GS_g_Legend {
            get {
                return ResourceManager.GetString("dlg_GS_g_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smoothing.
        /// </summary>
        public static string dlg_GS_g_Smoothing {
            get {
                return ResourceManager.GetString("dlg_GS_g_Smoothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font size:.
        /// </summary>
        public static string dlg_GS_lbl_Font {
            get {
                return ResourceManager.GetString("dlg_GS_lbl_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level of smoothing, pixels:.
        /// </summary>
        public static string dlg_GS_lbl_SmoothLevel {
            get {
                return ResourceManager.GetString("dlg_GS_lbl_SmoothLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphs preferences.
        /// </summary>
        public static string dlg_GS_Title {
            get {
                return ResourceManager.GetString("dlg_GS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to use:
        ///- Press Start or F9 to begin data collection in battle/test flight. Before you start check &quot;Altitude in feets&quot; setting;
        ///
        ///- To finish collection press Stop or F10
        ///
        ///- For data copying into Excel press appropriate button or use Ctrl+C/Ctrl+V.
        ///
        ///- PREFERENCES: At data collection preferences it is possible to add or remove input data filters. They blocks collection of data from fields with same names. Exact names you can check at http://127.0.0.1:8111/indicators and http://127.0.0.1:8111/state. [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string dlg_Help_Content {
            get {
                return ResourceManager.GetString("dlg_Help_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X-Axis:.
        /// </summary>
        public static string lbl_Abscissa {
            get {
                return ResourceManager.GetString("lbl_Abscissa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sources:.
        /// </summary>
        public static string lbl_Compare_Sources {
            get {
                return ResourceManager.GetString("lbl_Compare_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Y-Axis:.
        /// </summary>
        public static string lbl_Ordinata {
            get {
                return ResourceManager.GetString("lbl_Ordinata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data to show.
        /// </summary>
        public static string lbl_Params {
            get {
                return ResourceManager.GetString("lbl_Params", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection failed.
        /// </summary>
        public static string recorder_failed {
            get {
                return ResourceManager.GetString("recorder_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No data to save.
        /// </summary>
        public static string save_error {
            get {
                return ResourceManager.GetString("save_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data collection in progress. Press Stop or F10 to finish..
        /// </summary>
        public static string state_collecting {
            get {
                return ResourceManager.GetString("state_collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data collection finished with errors. Press start or F9 to collect new data..
        /// </summary>
        public static string state_failed {
            get {
                return ResourceManager.GetString("state_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Recorder {0} finished collection with error: {1}.
        /// </summary>
        public static string state_recorder_failed_format {
            get {
                return ResourceManager.GetString("state_recorder_failed_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data collection finished successfully! Press Start or F9 to collect new data..
        /// </summary>
        public static string state_success {
            get {
                return ResourceManager.GetString("state_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compare.
        /// </summary>
        public static string tab_Compare {
            get {
                return ResourceManager.GetString("tab_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Capture.
        /// </summary>
        public static string tab_Data {
            get {
                return ResourceManager.GetString("tab_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Graphs.
        /// </summary>
        public static string tab_Graph {
            get {
                return ResourceManager.GetString("tab_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Measures.
        /// </summary>
        public static string tab_Measures {
            get {
                return ResourceManager.GetString("tab_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WTParser v1.1.1.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
